; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = poller

[env:poller]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = +<common/> +<poller/> -<pult/>
lib_deps =
	AccelStepper
	fastled/FastLED@^3.7.7
	esp_now
monitor_filters = esp32_exception_decoder

[env:pult]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = +<common/> +<pult/> -<poller/>
lib_deps =
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	AsyncTCP
	esp_now
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
monitor_filters = esp32_exception_decoder
